# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'News Aggregator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for News Aggregator
  pod 'SnapKit', '~> 5.6.0'
  pod 'Alamofire'
end
